<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * Affinity is a group of affinity scheduling rules.
 */
class V1Affinity implements JsonSerializable
{
    /**
     * Describes node affinity scheduling rules for the pod.
     * @var V1NodeAffinity|null $nodeAffinity public property
     */
    public $nodeAffinity;

    /**
     * Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s)).
     * @var V1PodAffinity|null $podAffinity public property
     */
    public $podAffinity;

    /**
     * Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s)).
     * @var V1PodAffinity|null $podAntiAffinity public property
     */
    public $podAntiAffinity;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1NodeAffinity $nodeAffinity    Initialization value for $this->nodeAffinity
     * @param V1PodAffinity  $podAffinity     Initialization value for $this->podAffinity
     * @param V1PodAffinity  $podAntiAffinity Initialization value for $this->podAntiAffinity
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->nodeAffinity    = func_get_arg(0);
            $this->podAffinity     = func_get_arg(1);
            $this->podAntiAffinity = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['nodeAffinity']    = $this->nodeAffinity;
        $json['podAffinity']     = $this->podAffinity;
        $json['podAntiAffinity'] = $this->podAntiAffinity;

        return $json;
    }
}
