<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * APIResourceList is a list of APIResource, it is used to expose the name of the resources supported
 * in a specific group and version, and if the resource is namespaced.
 */
class V1APIResourceList implements JsonSerializable
{
    /**
     * groupVersion is the group and version this APIResourceList is for.
     * @required
     * @var string $groupVersion public property
     */
    public $groupVersion;

    /**
     * resources contains the name of the resources and if they are namespaced.
     * @required
     * @var V1APIResource[] $resources public property
     */
    public $resources;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $groupVersion Initialization value for $this->groupVersion
     * @param array  $resources    Initialization value for $this->resources
     * @param string $apiVersion   Initialization value for $this->apiVersion
     * @param string $kind         Initialization value for $this->kind
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->groupVersion = func_get_arg(0);
            $this->resources    = func_get_arg(1);
            $this->apiVersion   = func_get_arg(2);
            $this->kind         = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['groupVersion'] = $this->groupVersion;
        $json['resources']    = $this->resources;
        $json['apiVersion']   = $this->apiVersion;
        $json['kind']         = $this->kind;

        return $json;
    }
}
