<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * AttachedVolume describes a volume attached to a node
 */
class V1AttachedVolume implements JsonSerializable
{
    /**
     * DevicePath represents the device path where the volume should be available
     * @required
     * @var string $devicePath public property
     */
    public $devicePath;

    /**
     * Name of the attached volume
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $devicePath Initialization value for $this->devicePath
     * @param string $name       Initialization value for $this->name
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->devicePath = func_get_arg(0);
            $this->name       = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['devicePath'] = $this->devicePath;
        $json['name']       = $this->name;

        return $json;
    }
}
