<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * DeploymentSpec is the specification of the desired behavior of the Deployment.
 */
class V1beta1DeploymentSpec implements JsonSerializable
{
    /**
     * Template describes the pods that will be created.
     * @required
     * @var V1PodTemplateSpec $template public property
     */
    public $template;

    /**
     * Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)
     * @var integer|null $minReadySeconds public property
     */
    public $minReadySeconds;

    /**
     * Indicates that the deployment is paused and will not be processed by the deployment controller.
     * @var bool|null $paused public property
     */
    public $paused;

    /**
     * The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Once autoRollback is implemented, the deployment controller will automatically rollback failed deployments. Note that progress will not be estimated during the time a deployment is paused. This is not set by default.
     * @var integer|null $progressDeadlineSeconds public property
     */
    public $progressDeadlineSeconds;

    /**
     * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.
     * @var integer|null $replicas public property
     */
    public $replicas;

    /**
     * The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified.
     * @var integer|null $revisionHistoryLimit public property
     */
    public $revisionHistoryLimit;

    /**
     * The config this deployment is rolling back to. Will be cleared after rollback is done.
     * @var V1beta1RollbackConfig|null $rollbackTo public property
     */
    public $rollbackTo;

    /**
     * Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.
     * @var V1LabelSelector|null $selector public property
     */
    public $selector;

    /**
     * The deployment strategy to use to replace existing pods with new ones.
     * @var V1beta1DeploymentStrategy|null $strategy public property
     */
    public $strategy;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1PodTemplateSpec         $template                Initialization value for $this->template
     * @param integer                   $minReadySeconds         Initialization value for $this->minReadySeconds
     * @param bool                      $paused                  Initialization value for $this->paused
     * @param integer                   $progressDeadlineSeconds Initialization value for $this-
     *                                                             >progressDeadlineSeconds
     * @param integer                   $replicas                Initialization value for $this->replicas
     * @param integer                   $revisionHistoryLimit    Initialization value for $this->revisionHistoryLimit
     * @param V1beta1RollbackConfig     $rollbackTo              Initialization value for $this->rollbackTo
     * @param V1LabelSelector           $selector                Initialization value for $this->selector
     * @param V1beta1DeploymentStrategy $strategy                Initialization value for $this->strategy
     */
    public function __construct()
    {
        if (9 == func_num_args()) {
            $this->template                = func_get_arg(0);
            $this->minReadySeconds         = func_get_arg(1);
            $this->paused                  = func_get_arg(2);
            $this->progressDeadlineSeconds = func_get_arg(3);
            $this->replicas                = func_get_arg(4);
            $this->revisionHistoryLimit    = func_get_arg(5);
            $this->rollbackTo              = func_get_arg(6);
            $this->selector                = func_get_arg(7);
            $this->strategy                = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['template']                = $this->template;
        $json['minReadySeconds']         = $this->minReadySeconds;
        $json['paused']                  = $this->paused;
        $json['progressDeadlineSeconds'] = $this->progressDeadlineSeconds;
        $json['replicas']                = $this->replicas;
        $json['revisionHistoryLimit']    = $this->revisionHistoryLimit;
        $json['rollbackTo']              = $this->rollbackTo;
        $json['selector']                = $this->selector;
        $json['strategy']                = $this->strategy;

        return $json;
    }
}
