<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ClusterRoleBinding references a ClusterRole, but not contain it.  It can reference a ClusterRole in
 * the global namespace, and adds who information via Subject.
 */
class V1beta1ClusterRoleBinding implements JsonSerializable
{
    /**
     * RoleRef can only reference a ClusterRole in the global namespace. If the RoleRef cannot be resolved, the Authorizer must return an error.
     * @required
     * @var V1beta1RoleRef $roleRef public property
     */
    public $roleRef;

    /**
     * Subjects holds references to the objects the role applies to.
     * @required
     * @var V1beta1Subject[] $subjects public property
     */
    public $subjects;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * Standard object's metadata.
     * @var V1ObjectMeta|null $metadata public property
     */
    public $metadata;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1beta1RoleRef $roleRef    Initialization value for $this->roleRef
     * @param array          $subjects   Initialization value for $this->subjects
     * @param string         $apiVersion Initialization value for $this->apiVersion
     * @param string         $kind       Initialization value for $this->kind
     * @param V1ObjectMeta   $metadata   Initialization value for $this->metadata
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->roleRef    = func_get_arg(0);
            $this->subjects   = func_get_arg(1);
            $this->apiVersion = func_get_arg(2);
            $this->kind       = func_get_arg(3);
            $this->metadata   = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['roleRef']    = $this->roleRef;
        $json['subjects']   = $this->subjects;
        $json['apiVersion'] = $this->apiVersion;
        $json['kind']       = $this->kind;
        $json['metadata']   = $this->metadata;

        return $json;
    }
}
