<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class V1beta1CPUTargetUtilization implements JsonSerializable
{
    /**
     * fraction of the requested CPU that should be utilized/used, e.g. 70 means that 70% of the requested CPU should be in use.
     * @required
     * @var integer $targetPercentage public property
     */
    public $targetPercentage;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $targetPercentage Initialization value for $this->targetPercentage
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->targetPercentage = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['targetPercentage'] = $this->targetPercentage;

        return $json;
    }
}
