<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * IngressBackend describes all endpoints for a given service and port.
 */
class V1beta1IngressBackend implements JsonSerializable
{
    /**
     * Specifies the name of the referenced service.
     * @required
     * @var string $serviceName public property
     */
    public $serviceName;

    /**
     * Specifies the port of the referenced service.
     * @required
     * @var string $servicePort public property
     */
    public $servicePort;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $serviceName Initialization value for $this->serviceName
     * @param string $servicePort Initialization value for $this->servicePort
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->serviceName = func_get_arg(0);
            $this->servicePort = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['serviceName'] = $this->serviceName;
        $json['servicePort'] = $this->servicePort;

        return $json;
    }
}
