<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * This NetworkPolicyIngressRule matches traffic if and only if the traffic matches both ports AND from.
 */
class V1beta1NetworkPolicyIngressRule implements JsonSerializable
{
    /**
     * List of sources which should be able to access the pods selected for this rule. Items in this list are combined using a logical OR operation. If this field is not provided, this rule matches all sources (traffic not restricted by source). If this field is empty, this rule matches no sources (no traffic matches). If this field is present and contains at least on item, this rule allows traffic only if the traffic matches at least one item in the from list.
     * @var V1beta1NetworkPolicyPeer[]|null $from public property
     */
    public $from;

    /**
     * List of ports which should be made accessible on the pods selected for this rule. Each item in this list is combined using a logical OR. If this field is not provided, this rule matches all ports (traffic not restricted by port). If this field is empty, this rule matches no ports (no traffic matches). If this field is present and contains at least one item, then this rule allows traffic only if the traffic matches at least one port in the list.
     * @var V1beta1NetworkPolicyPort[]|null $ports public property
     */
    public $ports;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $from  Initialization value for $this->from
     * @param array $ports Initialization value for $this->ports
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->from  = func_get_arg(0);
            $this->ports = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['from']  = $this->from;
        $json['ports'] = $this->ports;

        return $json;
    }
}
