<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http:
 * //<host>/<path>?<searchpart> -> backend where where parts of the url correspond to RFC 3986, this
 * resource will be used to match against everything after the last '/' and before the first '?' or '#'.
 */
class V1beta1HTTPIngressRuleValue implements JsonSerializable
{
    /**
     * A collection of paths that map requests to backends.
     * @required
     * @var V1beta1HTTPIngressPath[] $paths public property
     */
    public $paths;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $paths Initialization value for $this->paths
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->paths = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['paths'] = $this->paths;

        return $json;
    }
}
