<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class V1beta1NetworkPolicyPort implements JsonSerializable
{
    /**
     * If specified, the port on the given protocol.  This can either be a numerical or named port on a pod.  If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.
     * @var string|null $port public property
     */
    public $port;

    /**
     * Optional.  The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP.
     * @var string|null $protocol public property
     */
    public $protocol;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $port     Initialization value for $this->port
     * @param string $protocol Initialization value for $this->protocol
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->port     = func_get_arg(0);
            $this->protocol = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['port']     = $this->port;
        $json['protocol'] = $this->protocol;

        return $json;
    }
}
