<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class V1beta1NetworkPolicySpec implements JsonSerializable
{
    /**
     * Selects the pods to which this NetworkPolicy object applies.  The array of ingress rules is applied to any pods selected by this field. Multiple network policies can select the same set of pods.  In this case, the ingress rules for each are combined additively. This field is NOT optional and follows standard label selector semantics. An empty podSelector matches all pods in this namespace.
     * @required
     * @var V1LabelSelector $podSelector public property
     */
    public $podSelector;

    /**
     * List of ingress rules to be applied to the selected pods. Traffic is allowed to a pod if namespace.networkPolicy.ingress.isolation is undefined and cluster policy allows it, OR if the traffic source is the pod's local node, OR if the traffic matches at least one ingress rule across all of the NetworkPolicy objects whose podSelector matches the pod. If this field is empty then this NetworkPolicy does not affect ingress isolation. If this field is present and contains at least one rule, this policy allows any traffic which matches at least one of the ingress rules in this list.
     * @var V1beta1NetworkPolicyIngressRule[]|null $ingress public property
     */
    public $ingress;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1LabelSelector $podSelector Initialization value for $this->podSelector
     * @param array           $ingress     Initialization value for $this->ingress
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->podSelector = func_get_arg(0);
            $this->ingress     = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['podSelector'] = $this->podSelector;
        $json['ingress']     = $this->ingress;

        return $json;
    }
}
