<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class V1beta1NetworkPolicyPeer implements JsonSerializable
{
    /**
     * Selects Namespaces using cluster scoped-labels.  This matches all pods in all namespaces selected by this label selector. This field follows standard label selector semantics. If omitted, this selector selects no namespaces. If present but empty, this selector selects all namespaces.
     * @var V1LabelSelector|null $namespaceSelector public property
     */
    public $namespaceSelector;

    /**
     * This is a label selector which selects Pods in this namespace. This field follows standard label selector semantics. If not provided, this selector selects no pods. If present but empty, this selector selects all pods in this namespace.
     * @var V1LabelSelector|null $podSelector public property
     */
    public $podSelector;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1LabelSelector $namespaceSelector Initialization value for $this->namespaceSelector
     * @param V1LabelSelector $podSelector       Initialization value for $this->podSelector
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->namespaceSelector = func_get_arg(0);
            $this->podSelector       = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['namespaceSelector'] = $this->namespaceSelector;
        $json['podSelector']       = $this->podSelector;

        return $json;
    }
}
