<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * DeploymentRollback stores the information required to rollback a deployment.
 */
class V1beta1DeploymentRollback implements JsonSerializable
{
    /**
     * Required: This must match the Name of a deployment.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The config of this deployment rollback.
     * @required
     * @var V1beta1RollbackConfig $rollbackTo public property
     */
    public $rollbackTo;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * The annotations to be updated to a deployment
     * @var array|null $updatedAnnotations public property
     */
    public $updatedAnnotations;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                $name               Initialization value for $this->name
     * @param V1beta1RollbackConfig $rollbackTo         Initialization value for $this->rollbackTo
     * @param string                $apiVersion         Initialization value for $this->apiVersion
     * @param string                $kind               Initialization value for $this->kind
     * @param array                 $updatedAnnotations Initialization value for $this->updatedAnnotations
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->name               = func_get_arg(0);
            $this->rollbackTo         = func_get_arg(1);
            $this->apiVersion         = func_get_arg(2);
            $this->kind               = func_get_arg(3);
            $this->updatedAnnotations = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']               = $this->name;
        $json['rollbackTo']         = $this->rollbackTo;
        $json['apiVersion']         = $this->apiVersion;
        $json['kind']               = $this->kind;
        $json['updatedAnnotations'] = $this->updatedAnnotations;

        return $json;
    }
}
