<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * BitbucketWebHookCause has information about a Bitbucket webhook that triggered a build.
 */
class V1BitbucketWebHookCause implements JsonSerializable
{
    /**
     * Revision is the git source revision information of the trigger.
     * @var V1SourceRevision|null $revision public property
     */
    public $revision;

    /**
     * Secret is the obfuscated webhook secret that triggered a build.
     * @var string|null $secret public property
     */
    public $secret;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1SourceRevision $revision Initialization value for $this->revision
     * @param string           $secret   Initialization value for $this->secret
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->revision = func_get_arg(0);
            $this->secret   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['revision'] = $this->revision;
        $json['secret']   = $this->secret;

        return $json;
    }
}
