<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * BuildStatusOutput contains the status of the built image.
 */
class V1BuildStatusOutput implements JsonSerializable
{
    /**
     * to describes the status of the built image being pushed to a registry.
     * @var V1BuildStatusOutputTo|null $to public property
     */
    public $to;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1BuildStatusOutputTo $to Initialization value for $this->to
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->to = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['to'] = $this->to;

        return $json;
    }
}
