<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ClusterPolicy is a object that holds all the ClusterRoles for a particular namespace.  There is at
 * most one ClusterPolicy document per namespace.
 */
class V1ClusterPolicy implements JsonSerializable
{
    /**
     * LastModified is the last time that any part of the ClusterPolicy was created, updated, or deleted
     * @required
     * @var string $lastModified public property
     */
    public $lastModified;

    /**
     * Roles holds all the ClusterRoles held by this ClusterPolicy, mapped by ClusterRole.Name
     * @required
     * @var V1NamedClusterRole[] $roles public property
     */
    public $roles;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * Standard object's metadata.
     * @var V1ObjectMeta|null $metadata public property
     */
    public $metadata;

    /**
     * Constructor to set initial or default values of member properties
     * @param string       $lastModified Initialization value for $this->lastModified
     * @param array        $roles        Initialization value for $this->roles
     * @param string       $apiVersion   Initialization value for $this->apiVersion
     * @param string       $kind         Initialization value for $this->kind
     * @param V1ObjectMeta $metadata     Initialization value for $this->metadata
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->lastModified = func_get_arg(0);
            $this->roles        = func_get_arg(1);
            $this->apiVersion   = func_get_arg(2);
            $this->kind         = func_get_arg(3);
            $this->metadata     = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['lastModified'] = $this->lastModified;
        $json['roles']        = $this->roles;
        $json['apiVersion']   = $this->apiVersion;
        $json['kind']         = $this->kind;
        $json['metadata']     = $this->metadata;

        return $json;
    }
}
