<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ClusterResourceQuotaStatus defines the actual enforced quota and its current usage
 */
class V1ClusterResourceQuotaStatus implements JsonSerializable
{
    /**
     * Namespaces slices the usage by project.  This division allows for quick resolution of deletion reconciliation inside of a single project without requiring a recalculation across all projects.  This can be used to pull the deltas for a given project.
     * @required
     * @var V1ResourceQuotaStatusByNamespace[] $namespaces public property
     */
    public $namespaces;

    /**
     * Total defines the actual enforced quota and its current usage across all projects
     * @required
     * @var V1ResourceQuotaStatus $total public property
     */
    public $total;

    /**
     * Constructor to set initial or default values of member properties
     * @param array                 $namespaces Initialization value for $this->namespaces
     * @param V1ResourceQuotaStatus $total      Initialization value for $this->total
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->namespaces = func_get_arg(0);
            $this->total      = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['namespaces'] = $this->namespaces;
        $json['total']      = $this->total;

        return $json;
    }
}
