<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * Adapts a ConfigMap into a volume.
 *
 * The contents of the target ConfigMap's Data field will be presented in a volume as files using the
 * keys in the Data field as the file names, unless the items element is populated with specific
 * mappings of keys to paths. ConfigMap volumes support ownership management and SELinux relabeling.
 */
class V1ConfigMapVolumeSource implements JsonSerializable
{
    /**
     * Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
     * @var integer|null $defaultMode public property
     */
    public $defaultMode;

    /**
     * If unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'.
     * @var V1KeyToPath[]|null $items public property
     */
    public $items;

    /**
     * Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names
     * @var string|null $name public property
     */
    public $name;

    /**
     * Specify whether the ConfigMap or it's keys must be defined
     * @var bool|null $optional public property
     */
    public $optional;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $defaultMode Initialization value for $this->defaultMode
     * @param array   $items       Initialization value for $this->items
     * @param string  $name        Initialization value for $this->name
     * @param bool    $optional    Initialization value for $this->optional
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->defaultMode = func_get_arg(0);
            $this->items       = func_get_arg(1);
            $this->name        = func_get_arg(2);
            $this->optional    = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['defaultMode'] = $this->defaultMode;
        $json['items']       = $this->items;
        $json['name']        = $this->name;
        $json['optional']    = $this->optional;

        return $json;
    }
}
