<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ContainerStateWaiting is a waiting state of a container.
 */
class V1ContainerStateWaiting implements JsonSerializable
{
    /**
     * Message regarding why the container is not yet running.
     * @var string|null $message public property
     */
    public $message;

    /**
     * (brief) reason the container is not yet running.
     * @var string|null $reason public property
     */
    public $reason;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $message Initialization value for $this->message
     * @param string $reason  Initialization value for $this->reason
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->message = func_get_arg(0);
            $this->reason  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['message'] = $this->message;
        $json['reason']  = $this->reason;

        return $json;
    }
}
