<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * Adapts a ConfigMap into a projected volume.
 *
 * The contents of the target ConfigMap's Data field will be presented in a projected volume as files
 * using the keys in the Data field as the file names, unless the items element is populated with
 * specific mappings of keys to paths. Note that this is identical to a configmap volume source without
 * the default mode.
 */
class V1ConfigMapProjection implements JsonSerializable
{
    /**
     * If unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'.
     * @var V1KeyToPath[]|null $items public property
     */
    public $items;

    /**
     * Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names
     * @var string|null $name public property
     */
    public $name;

    /**
     * Specify whether the ConfigMap or it's keys must be defined
     * @var bool|null $optional public property
     */
    public $optional;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $items    Initialization value for $this->items
     * @param string $name     Initialization value for $this->name
     * @param bool   $optional Initialization value for $this->optional
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->items    = func_get_arg(0);
            $this->name     = func_get_arg(1);
            $this->optional = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['items']    = $this->items;
        $json['name']     = $this->name;
        $json['optional'] = $this->optional;

        return $json;
    }
}
