<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * DeploymentConfigRollbackSpec represents the options for rollback generation.
 */
class V1DeploymentConfigRollbackSpec implements JsonSerializable
{
    /**
     * From points to a ReplicationController which is a deployment.
     * @required
     * @var V1ObjectReference $from public property
     */
    public $from;

    /**
     * IncludeReplicationMeta specifies whether to include the replica count and selector.
     * @required
     * @var bool $includeReplicationMeta public property
     */
    public $includeReplicationMeta;

    /**
     * IncludeStrategy specifies whether to include the deployment Strategy.
     * @required
     * @var bool $includeStrategy public property
     */
    public $includeStrategy;

    /**
     * IncludeTemplate specifies whether to include the PodTemplateSpec.
     * @required
     * @var bool $includeTemplate public property
     */
    public $includeTemplate;

    /**
     * IncludeTriggers specifies whether to include config Triggers.
     * @required
     * @var bool $includeTriggers public property
     */
    public $includeTriggers;

    /**
     * Revision to rollback to. If set to 0, rollback to the last revision.
     * @var integer|null $revision public property
     */
    public $revision;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1ObjectReference $from                   Initialization value for $this->from
     * @param bool              $includeReplicationMeta Initialization value for $this->includeReplicationMeta
     * @param bool              $includeStrategy        Initialization value for $this->includeStrategy
     * @param bool              $includeTemplate        Initialization value for $this->includeTemplate
     * @param bool              $includeTriggers        Initialization value for $this->includeTriggers
     * @param integer           $revision               Initialization value for $this->revision
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->from                   = func_get_arg(0);
            $this->includeReplicationMeta = func_get_arg(1);
            $this->includeStrategy        = func_get_arg(2);
            $this->includeTemplate        = func_get_arg(3);
            $this->includeTriggers        = func_get_arg(4);
            $this->revision               = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['from']                   = $this->from;
        $json['includeReplicationMeta'] = $this->includeReplicationMeta;
        $json['includeStrategy']        = $this->includeStrategy;
        $json['includeTemplate']        = $this->includeTemplate;
        $json['includeTriggers']        = $this->includeTriggers;
        $json['revision']               = $this->revision;

        return $json;
    }
}
