<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * DeploymentConfigRollback provides the input to rollback generation.
 */
class V1DeploymentConfigRollback implements JsonSerializable
{
    /**
     * Name of the deployment config that will be rolled back.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Spec defines the options to rollback generation.
     * @required
     * @var V1DeploymentConfigRollbackSpec $spec public property
     */
    public $spec;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * UpdatedAnnotations is a set of new annotations that will be added in the deployment config.
     * @var array|null $updatedAnnotations public property
     */
    public $updatedAnnotations;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                         $name               Initialization value for $this->name
     * @param V1DeploymentConfigRollbackSpec $spec               Initialization value for $this->spec
     * @param string                         $apiVersion         Initialization value for $this->apiVersion
     * @param string                         $kind               Initialization value for $this->kind
     * @param array                          $updatedAnnotations Initialization value for $this->updatedAnnotations
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->name               = func_get_arg(0);
            $this->spec               = func_get_arg(1);
            $this->apiVersion         = func_get_arg(2);
            $this->kind               = func_get_arg(3);
            $this->updatedAnnotations = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']               = $this->name;
        $json['spec']               = $this->spec;
        $json['apiVersion']         = $this->apiVersion;
        $json['kind']               = $this->kind;
        $json['updatedAnnotations'] = $this->updatedAnnotations;

        return $json;
    }
}
