<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * DeploymentRequest is a request to a deployment config for a new deployment.
 */
class V1DeploymentRequest implements JsonSerializable
{
    /**
     * Force will try to force a new deployment to run. If the deployment config is paused, then setting this to true will return an Invalid error.
     * @required
     * @var bool $force public property
     */
    public $force;

    /**
     * Latest will update the deployment config with the latest state from all triggers.
     * @required
     * @var bool $latest public property
     */
    public $latest;

    /**
     * Name of the deployment config for requesting a new deployment.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool   $force      Initialization value for $this->force
     * @param bool   $latest     Initialization value for $this->latest
     * @param string $name       Initialization value for $this->name
     * @param string $apiVersion Initialization value for $this->apiVersion
     * @param string $kind       Initialization value for $this->kind
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->force      = func_get_arg(0);
            $this->latest     = func_get_arg(1);
            $this->name       = func_get_arg(2);
            $this->apiVersion = func_get_arg(3);
            $this->kind       = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['force']      = $this->force;
        $json['latest']     = $this->latest;
        $json['name']       = $this->name;
        $json['apiVersion'] = $this->apiVersion;
        $json['kind']       = $this->kind;

        return $json;
    }
}
