<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * DeleteOptions may be provided when deleting an API object.
 */
class V1DeleteOptions implements JsonSerializable
{
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
     * @var integer|null $gracePeriodSeconds public property
     */
    public $gracePeriodSeconds;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the "orphan" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
     * @var bool|null $orphanDependents public property
     */
    public $orphanDependents;

    /**
     * Must be fulfilled before a deletion is carried out. If not possible, a 409 Conflict status will be returned.
     * @var V1Preconditions|null $preconditions public property
     */
    public $preconditions;

    /**
     * Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy.
     * @var string|null $propagationPolicy public property
     */
    public $propagationPolicy;

    /**
     * Constructor to set initial or default values of member properties
     * @param string          $apiVersion         Initialization value for $this->apiVersion
     * @param integer         $gracePeriodSeconds Initialization value for $this->gracePeriodSeconds
     * @param string          $kind               Initialization value for $this->kind
     * @param bool            $orphanDependents   Initialization value for $this->orphanDependents
     * @param V1Preconditions $preconditions      Initialization value for $this->preconditions
     * @param string          $propagationPolicy  Initialization value for $this->propagationPolicy
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->apiVersion         = func_get_arg(0);
            $this->gracePeriodSeconds = func_get_arg(1);
            $this->kind               = func_get_arg(2);
            $this->orphanDependents   = func_get_arg(3);
            $this->preconditions      = func_get_arg(4);
            $this->propagationPolicy  = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['apiVersion']         = $this->apiVersion;
        $json['gracePeriodSeconds'] = $this->gracePeriodSeconds;
        $json['kind']               = $this->kind;
        $json['orphanDependents']   = $this->orphanDependents;
        $json['preconditions']      = $this->preconditions;
        $json['propagationPolicy']  = $this->propagationPolicy;

        return $json;
    }
}
