<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * Represents downward API info for projecting into a projected volume. Note that this is identical to
 * a downwardAPI volume source without the default mode.
 */
class V1DownwardAPIProjection implements JsonSerializable
{
    /**
     * Items is a list of DownwardAPIVolume file
     * @var V1DownwardAPIVolumeFile[]|null $items public property
     */
    public $items;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $items Initialization value for $this->items
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->items = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['items'] = $this->items;

        return $json;
    }
}
