<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * EndpointPort is a tuple that describes a single port.
 */
class V1EndpointPort implements JsonSerializable
{
    /**
     * The port number of the endpoint.
     * @required
     * @var integer $port public property
     */
    public $port;

    /**
     * The name of this port (corresponds to ServicePort.Name). Must be a DNS_LABEL. Optional only if one port is defined.
     * @var string|null $name public property
     */
    public $name;

    /**
     * The IP protocol for this port. Must be UDP or TCP. Default is TCP.
     * @var string|null $protocol public property
     */
    public $protocol;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $port     Initialization value for $this->port
     * @param string  $name     Initialization value for $this->name
     * @param string  $protocol Initialization value for $this->protocol
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->port     = func_get_arg(0);
            $this->name     = func_get_arg(1);
            $this->protocol = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['port']     = $this->port;
        $json['name']     = $this->name;
        $json['protocol'] = $this->protocol;

        return $json;
    }
}
