<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * EventSource contains information for an event.
 */
class V1EventSource implements JsonSerializable
{
    /**
     * Component from which the event is generated.
     * @var string|null $component public property
     */
    public $component;

    /**
     * Node name on which the event is generated.
     * @var string|null $host public property
     */
    public $host;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $component Initialization value for $this->component
     * @param string $host      Initialization value for $this->host
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->component = func_get_arg(0);
            $this->host      = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['component'] = $this->component;
        $json['host']      = $this->host;

        return $json;
    }
}
