<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ExecAction describes a "run in container" action.
 */
class V1ExecAction implements JsonSerializable
{
    /**
     * Command is the command line to execute inside the container, the working directory for the command  is root ('/') in the container's filesystem. The command is simply exec'd, it is not run inside a shell, so traditional shell instructions ('|', etc) won't work. To use a shell, you need to explicitly call out to that shell. Exit status of 0 is treated as live/healthy and non-zero is unhealthy.
     * @var array|null $command public property
     */
    public $command;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $command Initialization value for $this->command
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->command = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['command'] = $this->command;

        return $json;
    }
}
