<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * FSGroupStrategyOptions defines the strategy type and options used to create the strategy.
 */
class V1FSGroupStrategyOptions implements JsonSerializable
{
    /**
     * Ranges are the allowed ranges of fs groups.  If you would like to force a single fs group then supply a single range with the same start and end.
     * @var V1IDRange[]|null $ranges public property
     */
    public $ranges;

    /**
     * Type is the strategy that will dictate what FSGroup is used in the SecurityContext.
     * @var string|null $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $ranges Initialization value for $this->ranges
     * @param string $type   Initialization value for $this->type
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->ranges = func_get_arg(0);
            $this->type   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ranges'] = $this->ranges;
        $json['type']   = $this->type;

        return $json;
    }
}
