<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * Represents a volume that is populated with the contents of a git repository. Git repo volumes do not
 * support ownership management. Git repo volumes support SELinux relabeling.
 */
class V1GitRepoVolumeSource implements JsonSerializable
{
    /**
     * Repository URL
     * @required
     * @var string $repository public property
     */
    public $repository;

    /**
     * Target directory name. Must not contain or start with '..'.  If '.' is supplied, the volume directory will be the git repository.  Otherwise, if specified, the volume will contain the git repository in the subdirectory with the given name.
     * @var string|null $directory public property
     */
    public $directory;

    /**
     * Commit hash for the specified revision.
     * @var string|null $revision public property
     */
    public $revision;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $repository Initialization value for $this->repository
     * @param string $directory  Initialization value for $this->directory
     * @param string $revision   Initialization value for $this->revision
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->repository = func_get_arg(0);
            $this->directory  = func_get_arg(1);
            $this->revision   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['repository'] = $this->repository;
        $json['directory']  = $this->directory;
        $json['revision']   = $this->revision;

        return $json;
    }
}
