<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * GroupRestriction matches a group either by a string match on the group name or a label selector
 * applied to group labels.
 */
class V1GroupRestriction implements JsonSerializable
{
    /**
     * Groups is a list of groups used to match against an individual user's groups. If the user is a member of one of the whitelisted groups, the user is allowed to be bound to a role.
     * @required
     * @var array $groups public property
     */
    public $groups;

    /**
     * Selectors specifies a list of label selectors over group labels.
     * @required
     * @var V1LabelSelector[] $labels public property
     */
    public $labels;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $groups Initialization value for $this->groups
     * @param array $labels Initialization value for $this->labels
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->groups = func_get_arg(0);
            $this->labels = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['groups'] = $this->groups;
        $json['labels'] = $this->labels;

        return $json;
    }
}
