<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ImageStreamImportStatus contains information about the status of an image stream import.
 */
class V1ImageStreamImportStatus implements JsonSerializable
{
    /**
     * Images is set with the result of importing spec.images
     * @var V1ImageImportStatus[]|null $images public property
     */
    public $images;

    /**
     * Import is the image stream that was successfully updated or created when 'to' was set.
     * @var V1ImageStream|null $import public property
     */
    public $import;

    /**
     * Repository is set if spec.repository was set to the outcome of the import
     * @var V1RepositoryImportStatus|null $repository public property
     */
    public $repository;

    /**
     * Constructor to set initial or default values of member properties
     * @param array                    $images     Initialization value for $this->images
     * @param V1ImageStream            $import     Initialization value for $this->import
     * @param V1RepositoryImportStatus $repository Initialization value for $this->repository
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->images     = func_get_arg(0);
            $this->import     = func_get_arg(1);
            $this->repository = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['images']     = $this->images;
        $json['import']     = $this->import;
        $json['repository'] = $this->repository;

        return $json;
    }
}
