<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ImageImportStatus describes the result of an image import.
 */
class V1ImageImportStatus implements JsonSerializable
{
    /**
     * Status is the status of the image import, including errors encountered while retrieving the image
     * @required
     * @var V1Status $status public property
     */
    public $status;

    /**
     * Image is the metadata of that image, if the image was located
     * @var V1Image|null $image public property
     */
    public $image;

    /**
     * Tag is the tag this image was located under, if any
     * @var string|null $tag public property
     */
    public $tag;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1Status $status Initialization value for $this->status
     * @param V1Image  $image  Initialization value for $this->image
     * @param string   $tag    Initialization value for $this->tag
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->status = func_get_arg(0);
            $this->image  = func_get_arg(1);
            $this->tag    = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['status'] = $this->status;
        $json['image']  = $this->image;
        $json['tag']    = $this->tag;

        return $json;
    }
}
