<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ImageChangeCause contains information about the image that triggered a build
 */
class V1ImageChangeCause implements JsonSerializable
{
    /**
     * fromRef contains detailed information about an image that triggered a build.
     * @var V1ObjectReference|null $fromRef public property
     */
    public $fromRef;

    /**
     * imageID is the ID of the image that triggered a a new build.
     * @var string|null $imageID public property
     */
    public $imageID;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1ObjectReference $fromRef Initialization value for $this->fromRef
     * @param string            $imageID Initialization value for $this->imageID
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->fromRef = func_get_arg(0);
            $this->imageID = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['fromRef'] = $this->fromRef;
        $json['imageID'] = $this->imageID;

        return $json;
    }
}
