<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ImageChangeTrigger allows builds to be triggered when an ImageStream changes
 */
class V1ImageChangeTrigger implements JsonSerializable
{
    /**
     * from is a reference to an ImageStreamTag that will trigger a build when updated It is optional. If no From is specified, the From image from the build strategy will be used. Only one ImageChangeTrigger with an empty From reference is allowed in a build configuration.
     * @var V1ObjectReference|null $from public property
     */
    public $from;

    /**
     * lastTriggeredImageID is used internally by the ImageChangeController to save last used image ID for build
     * @var string|null $lastTriggeredImageID public property
     */
    public $lastTriggeredImageID;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1ObjectReference $from                 Initialization value for $this->from
     * @param string            $lastTriggeredImageID Initialization value for $this->lastTriggeredImageID
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->from                 = func_get_arg(0);
            $this->lastTriggeredImageID = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['from']                 = $this->from;
        $json['lastTriggeredImageID'] = $this->lastTriggeredImageID;

        return $json;
    }
}
