<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * JenkinsPipelineBuildStrategy holds parameters specific to a Jenkins Pipeline build. This strategy is
 * in tech preview.
 */
class V1JenkinsPipelineBuildStrategy implements JsonSerializable
{
    /**
     * env contains additional environment variables you want to pass into a build pipeline. ValueFrom is not supported.
     * @var V1EnvVar[]|null $env public property
     */
    public $env;

    /**
     * Jenkinsfile defines the optional raw contents of a Jenkinsfile which defines a Jenkins pipeline build.
     * @var string|null $jenkinsfile public property
     */
    public $jenkinsfile;

    /**
     * JenkinsfilePath is the optional path of the Jenkinsfile that will be used to configure the pipeline relative to the root of the context (contextDir). If both JenkinsfilePath & Jenkinsfile are both not specified, this defaults to Jenkinsfile in the root of the specified contextDir.
     * @var string|null $jenkinsfilePath public property
     */
    public $jenkinsfilePath;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $env             Initialization value for $this->env
     * @param string $jenkinsfile     Initialization value for $this->jenkinsfile
     * @param string $jenkinsfilePath Initialization value for $this->jenkinsfilePath
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->env             = func_get_arg(0);
            $this->jenkinsfile     = func_get_arg(1);
            $this->jenkinsfilePath = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['env']             = $this->env;
        $json['jenkinsfile']     = $this->jenkinsfile;
        $json['jenkinsfilePath'] = $this->jenkinsfilePath;

        return $json;
    }
}
