<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * JobStatus represents the current state of a Job.
 */
class V1JobStatus implements JsonSerializable
{
    /**
     * Active is the number of actively running pods.
     * @var integer|null $active public property
     */
    public $active;

    /**
     * CompletionTime represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
     * @var string|null $completionTime public property
     */
    public $completionTime;

    /**
     * Conditions represent the latest available observations of an object's current state. More info: http://kubernetes.io/docs/user-guide/jobs
     * @var V1SignatureCondition[]|null $conditions public property
     */
    public $conditions;

    /**
     * Failed is the number of pods which reached Phase Failed.
     * @var integer|null $failed public property
     */
    public $failed;

    /**
     * StartTime represents time when the job was acknowledged by the Job Manager. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
     * @var string|null $startTime public property
     */
    public $startTime;

    /**
     * Succeeded is the number of pods which reached Phase Succeeded.
     * @var integer|null $succeeded public property
     */
    public $succeeded;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $active         Initialization value for $this->active
     * @param string  $completionTime Initialization value for $this->completionTime
     * @param array   $conditions     Initialization value for $this->conditions
     * @param integer $failed         Initialization value for $this->failed
     * @param string  $startTime      Initialization value for $this->startTime
     * @param integer $succeeded      Initialization value for $this->succeeded
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->active         = func_get_arg(0);
            $this->completionTime = func_get_arg(1);
            $this->conditions     = func_get_arg(2);
            $this->failed         = func_get_arg(3);
            $this->startTime      = func_get_arg(4);
            $this->succeeded      = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['active']         = $this->active;
        $json['completionTime'] = $this->completionTime;
        $json['conditions']     = $this->conditions;
        $json['failed']         = $this->failed;
        $json['startTime']      = $this->startTime;
        $json['succeeded']      = $this->succeeded;

        return $json;
    }
}
