<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * Maps a string key to a path within a volume.
 */
class V1KeyToPath implements JsonSerializable
{
    /**
     * The key to project.
     * @required
     * @var string $key public property
     */
    public $key;

    /**
     * The relative path of the file to map the key to. May not be an absolute path. May not contain the path element '..'. May not start with the string '..'.
     * @required
     * @var string $path public property
     */
    public $path;

    /**
     * Optional: mode bits to use on this file, must be a value between 0 and 0777. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
     * @var integer|null $mode public property
     */
    public $mode;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $key  Initialization value for $this->key
     * @param string  $path Initialization value for $this->path
     * @param integer $mode Initialization value for $this->mode
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->key  = func_get_arg(0);
            $this->path = func_get_arg(1);
            $this->mode = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['key']  = $this->key;
        $json['path'] = $this->path;
        $json['mode'] = $this->mode;

        return $json;
    }
}
