<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * LifecycleHook defines a specific deployment lifecycle action. Only one type of action may be
 * specified at any time.
 */
class V1LifecycleHook implements JsonSerializable
{
    /**
     * FailurePolicy specifies what action to take if the hook fails.
     * @required
     * @var string $failurePolicy public property
     */
    public $failurePolicy;

    /**
     * ExecNewPod specifies the options for a lifecycle hook backed by a pod.
     * @var V1ExecNewPodHook|null $execNewPod public property
     */
    public $execNewPod;

    /**
     * TagImages instructs the deployer to tag the current image referenced under a container onto an image stream tag.
     * @var V1TagImageHook[]|null $tagImages public property
     */
    public $tagImages;

    /**
     * Constructor to set initial or default values of member properties
     * @param string           $failurePolicy Initialization value for $this->failurePolicy
     * @param V1ExecNewPodHook $execNewPod    Initialization value for $this->execNewPod
     * @param array            $tagImages     Initialization value for $this->tagImages
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->failurePolicy = func_get_arg(0);
            $this->execNewPod    = func_get_arg(1);
            $this->tagImages     = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['failurePolicy'] = $this->failurePolicy;
        $json['execNewPod']    = $this->execNewPod;
        $json['tagImages']     = $this->tagImages;

        return $json;
    }
}
