<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * LoadBalancerStatus represents the status of a load-balancer.
 */
class V1LoadBalancerStatus implements JsonSerializable
{
    /**
     * Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
     * @var V1LoadBalancerIngress[]|null $ingress public property
     */
    public $ingress;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $ingress Initialization value for $this->ingress
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->ingress = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ingress'] = $this->ingress;

        return $json;
    }
}
