<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * NamespaceStatus is information about the current status of a Namespace.
 */
class V1NamespaceStatus implements JsonSerializable
{
    /**
     * Phase is the current lifecycle phase of the namespace. More info: http://releases.k8s.io/HEAD/docs/design/namespaces.md#phases
     * @var string|null $phase public property
     */
    public $phase;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $phase Initialization value for $this->phase
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->phase = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['phase'] = $this->phase;

        return $json;
    }
}
