<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * NamedTagEventList relates a tag to its image history.
 */
class V1NamedTagEventList implements JsonSerializable
{
    /**
     * Standard object's metadata.
     * @required
     * @var V1TagEvent[] $items public property
     */
    public $items;

    /**
     * Tag is the tag for which the history is recorded
     * @required
     * @var string $tag public property
     */
    public $tag;

    /**
     * Conditions is an array of conditions that apply to the tag event list.
     * @var V1TagEventCondition[]|null $conditions public property
     */
    public $conditions;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $items      Initialization value for $this->items
     * @param string $tag        Initialization value for $this->tag
     * @param array  $conditions Initialization value for $this->conditions
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->items      = func_get_arg(0);
            $this->tag        = func_get_arg(1);
            $this->conditions = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['items']      = $this->items;
        $json['tag']        = $this->tag;
        $json['conditions'] = $this->conditions;

        return $json;
    }
}
