<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * NamedClusterRole relates a name with a cluster role
 */
class V1NamedClusterRole implements JsonSerializable
{
    /**
     * Name is the name of the cluster role
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Role is the cluster role being named
     * @required
     * @var V1ClusterRole $role public property
     */
    public $role;

    /**
     * Constructor to set initial or default values of member properties
     * @param string        $name Initialization value for $this->name
     * @param V1ClusterRole $role Initialization value for $this->role
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->name = func_get_arg(0);
            $this->role = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name'] = $this->name;
        $json['role'] = $this->role;

        return $json;
    }
}
