<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * A null or empty node selector term matches no objects.
 */
class V1NodeSelectorTerm implements JsonSerializable
{
    /**
     * Required. A list of node selector requirements. The requirements are ANDed.
     * @required
     * @var V1NodeSelectorRequirement[] $matchExpressions public property
     */
    public $matchExpressions;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $matchExpressions Initialization value for $this->matchExpressions
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->matchExpressions = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['matchExpressions'] = $this->matchExpressions;

        return $json;
    }
}
