<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * Node affinity is a group of node affinity scheduling rules.
 */
class V1NodeAffinity implements JsonSerializable
{
    /**
     * The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.
     * @var V1PreferredSchedulingTerm[]|null $preferredDuringSchedulingIgnoredDuringExecution public property
     */
    public $preferredDuringSchedulingIgnoredDuringExecution;

    /**
     * If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node.
     * @var V1NodeSelector|null $requiredDuringSchedulingIgnoredDuringExecution public property
     */
    public $requiredDuringSchedulingIgnoredDuringExecution;

    /**
     * Constructor to set initial or default values of member properties
     * @param array          $preferredDuringSchedulingIgnoredDuringExecution Initialization value for $this-
     *                                                                          >preferredDuringSchedulingIgnoredDuringE
     *                                                                          xecution
     * @param V1NodeSelector $requiredDuringSchedulingIgnoredDuringExecution  Initialization value for $this-
     *                                                                          >requiredDuringSchedulingIgnoredDuringEx
     *                                                                          ecution
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->preferredDuringSchedulingIgnoredDuringExecution = func_get_arg(0);
            $this->requiredDuringSchedulingIgnoredDuringExecution  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['preferredDuringSchedulingIgnoredDuringExecution'] = $this->preferredDuringSchedulingIgnoredDuringExecution;
        $json['requiredDuringSchedulingIgnoredDuringExecution']  = $this->requiredDuringSchedulingIgnoredDuringExecution;

        return $json;
    }
}
