<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * NodeAddress contains information for the node's address.
 */
class V1NodeAddress implements JsonSerializable
{
    /**
     * The node address.
     * @required
     * @var string $address public property
     */
    public $address;

    /**
     * Node address type, one of Hostname, ExternalIP or InternalIP.
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $address Initialization value for $this->address
     * @param string $type    Initialization value for $this->type
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->address = func_get_arg(0);
            $this->type    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['address'] = $this->address;
        $json['type']    = $this->type;

        return $json;
    }
}
