<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * NodeSpec describes the attributes that a node is created with.
 */
class V1NodeSpec implements JsonSerializable
{
    /**
     * External ID of the node assigned by some machine database (e.g. a cloud provider). Deprecated.
     * @var string|null $externalID public property
     */
    public $externalID;

    /**
     * PodCIDR represents the pod IP range assigned to the node.
     * @var string|null $podCIDR public property
     */
    public $podCIDR;

    /**
     * ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>
     * @var string|null $providerID public property
     */
    public $providerID;

    /**
     * If specified, the node's taints.
     * @var V1Taint[]|null $taints public property
     */
    public $taints;

    /**
     * Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#manual-node-administration
     * @var bool|null $unschedulable public property
     */
    public $unschedulable;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $externalID    Initialization value for $this->externalID
     * @param string $podCIDR       Initialization value for $this->podCIDR
     * @param string $providerID    Initialization value for $this->providerID
     * @param array  $taints        Initialization value for $this->taints
     * @param bool   $unschedulable Initialization value for $this->unschedulable
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->externalID    = func_get_arg(0);
            $this->podCIDR       = func_get_arg(1);
            $this->providerID    = func_get_arg(2);
            $this->taints        = func_get_arg(3);
            $this->unschedulable = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['externalID']    = $this->externalID;
        $json['podCIDR']       = $this->podCIDR;
        $json['providerID']    = $this->providerID;
        $json['taints']        = $this->taints;
        $json['unschedulable'] = $this->unschedulable;

        return $json;
    }
}
