<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ObjectFieldSelector selects an APIVersioned field of an object.
 */
class V1ObjectFieldSelector implements JsonSerializable
{
    /**
     * Path of the field to select in the specified API version.
     * @required
     * @var string $fieldPath public property
     */
    public $fieldPath;

    /**
     * Version of the schema the FieldPath is written in terms of, defaults to "v1".
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $fieldPath  Initialization value for $this->fieldPath
     * @param string $apiVersion Initialization value for $this->apiVersion
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->fieldPath  = func_get_arg(0);
            $this->apiVersion = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['fieldPath']  = $this->fieldPath;
        $json['apiVersion'] = $this->apiVersion;

        return $json;
    }
}
