<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must
 * create.
 */
class V1ObjectMeta implements JsonSerializable
{
    /**
     * Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations
     * @var array|null $annotations public property
     */
    public $annotations;

    /**
     * The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.
     * @var string|null $clusterName public property
     */
    public $clusterName;

    /**
     * CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
     * Populated by the system. Read-only. Null for lists. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata
     * @var string|null $creationTimestamp public property
     */
    public $creationTimestamp;

    /**
     * Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
     * @var integer|null $deletionGracePeriodSeconds public property
     */
    public $deletionGracePeriodSeconds;

    /**
     * DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field. Once set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.
     * Populated by the system when a graceful deletion is requested. Read-only. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata
     * @var string|null $deletionTimestamp public property
     */
    public $deletionTimestamp;

    /**
     * Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed.
     * @var array|null $finalizers public property
     */
    public $finalizers;

    /**
     * GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.
     * If this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).
     * Applied only if Name is not specified. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#idempotency
     * @var string|null $generateName public property
     */
    public $generateName;

    /**
     * A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
     * @var integer|null $generation public property
     */
    public $generation;

    /**
     * Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels
     * @var array|null $labels public property
     */
    public $labels;

    /**
     * Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names
     * @var string|null $name public property
     */
    public $name;

    /**
     * Namespace defines the space within each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.
     * Must be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces
     * @maps namespace
     * @var string|null $mnamespace public property
     */
    public $mnamespace;

    /**
     * List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
     * @var V1OwnerReference[]|null $ownerReferences public property
     */
    public $ownerReferences;

    /**
     * An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.
     * Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#concurrency-control-and-consistency
     * @var string|null $resourceVersion public property
     */
    public $resourceVersion;

    /**
     * SelfLink is a URL representing this object. Populated by the system. Read-only.
     * @var string|null $selfLink public property
     */
    public $selfLink;

    /**
     * UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.
     * Populated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids
     * @var string|null $uid public property
     */
    public $uid;

    /**
     * Constructor to set initial or default values of member properties
     * @param array   $annotations                Initialization value for $this->annotations
     * @param string  $clusterName                Initialization value for $this->clusterName
     * @param string  $creationTimestamp          Initialization value for $this->creationTimestamp
     * @param integer $deletionGracePeriodSeconds Initialization value for $this->deletionGracePeriodSeconds
     * @param string  $deletionTimestamp          Initialization value for $this->deletionTimestamp
     * @param array   $finalizers                 Initialization value for $this->finalizers
     * @param string  $generateName               Initialization value for $this->generateName
     * @param integer $generation                 Initialization value for $this->generation
     * @param array   $labels                     Initialization value for $this->labels
     * @param string  $name                       Initialization value for $this->name
     * @param string  $mnamespace                 Initialization value for $this->mnamespace
     * @param array   $ownerReferences            Initialization value for $this->ownerReferences
     * @param string  $resourceVersion            Initialization value for $this->resourceVersion
     * @param string  $selfLink                   Initialization value for $this->selfLink
     * @param string  $uid                        Initialization value for $this->uid
     */
    public function __construct()
    {
        if (15 == func_num_args()) {
            $this->annotations                = func_get_arg(0);
            $this->clusterName                = func_get_arg(1);
            $this->creationTimestamp          = func_get_arg(2);
            $this->deletionGracePeriodSeconds = func_get_arg(3);
            $this->deletionTimestamp          = func_get_arg(4);
            $this->finalizers                 = func_get_arg(5);
            $this->generateName               = func_get_arg(6);
            $this->generation                 = func_get_arg(7);
            $this->labels                     = func_get_arg(8);
            $this->name                       = func_get_arg(9);
            $this->mnamespace                 = func_get_arg(10);
            $this->ownerReferences            = func_get_arg(11);
            $this->resourceVersion            = func_get_arg(12);
            $this->selfLink                   = func_get_arg(13);
            $this->uid                        = func_get_arg(14);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['annotations']                = $this->annotations;
        $json['clusterName']                = $this->clusterName;
        $json['creationTimestamp']          = $this->creationTimestamp;
        $json['deletionGracePeriodSeconds'] = $this->deletionGracePeriodSeconds;
        $json['deletionTimestamp']          = $this->deletionTimestamp;
        $json['finalizers']                 = $this->finalizers;
        $json['generateName']               = $this->generateName;
        $json['generation']                 = $this->generation;
        $json['labels']                     = $this->labels;
        $json['name']                       = $this->name;
        $json['namespace']                  = $this->mnamespace;
        $json['ownerReferences']            = $this->ownerReferences;
        $json['resourceVersion']            = $this->resourceVersion;
        $json['selfLink']                   = $this->selfLink;
        $json['uid']                        = $this->uid;

        return $json;
    }
}
