<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * OwnerReference contains enough information to let you identify an owning object. Currently, an
 * owning object must be in the same namespace, so there is no namespace field.
 */
class V1OwnerReference implements JsonSerializable
{
    /**
     * API version of the referent.
     * @required
     * @var string $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind of the referent. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @required
     * @var string $kind public property
     */
    public $kind;

    /**
     * Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids
     * @required
     * @var string $uid public property
     */
    public $uid;

    /**
     * If true, AND if the owner has the "foregroundDeletion" finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs "delete" permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.
     * @var bool|null $blockOwnerDeletion public property
     */
    public $blockOwnerDeletion;

    /**
     * If true, this reference points to the managing controller.
     * @var bool|null $controller public property
     */
    public $controller;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $apiVersion         Initialization value for $this->apiVersion
     * @param string $kind               Initialization value for $this->kind
     * @param string $name               Initialization value for $this->name
     * @param string $uid                Initialization value for $this->uid
     * @param bool   $blockOwnerDeletion Initialization value for $this->blockOwnerDeletion
     * @param bool   $controller         Initialization value for $this->controller
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->apiVersion         = func_get_arg(0);
            $this->kind               = func_get_arg(1);
            $this->name               = func_get_arg(2);
            $this->uid                = func_get_arg(3);
            $this->blockOwnerDeletion = func_get_arg(4);
            $this->controller         = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['apiVersion']         = $this->apiVersion;
        $json['kind']               = $this->kind;
        $json['name']               = $this->name;
        $json['uid']                = $this->uid;
        $json['blockOwnerDeletion'] = $this->blockOwnerDeletion;
        $json['controller']         = $this->controller;

        return $json;
    }
}
