<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * PersistentVolumeClaimVolumeSource references the user's PVC in the same namespace. This volume finds
 * the bound PV and mounts that volume for the pod. A PersistentVolumeClaimVolumeSource is, essentially,
 * a wrapper around another type of volume that is owned by someone else (the system).
 */
class V1PersistentVolumeClaimVolumeSource implements JsonSerializable
{
    /**
     * ClaimName is the name of a PersistentVolumeClaim in the same namespace as the pod using this volume. More info: http://kubernetes.io/docs/user-guide/persistent-volumes#persistentvolumeclaims
     * @required
     * @var string $claimName public property
     */
    public $claimName;

    /**
     * Will force the ReadOnly setting in VolumeMounts. Default false.
     * @var bool|null $readOnly public property
     */
    public $readOnly;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $claimName Initialization value for $this->claimName
     * @param bool   $readOnly  Initialization value for $this->readOnly
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->claimName = func_get_arg(0);
            $this->readOnly  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['claimName'] = $this->claimName;
        $json['readOnly']  = $this->readOnly;

        return $json;
    }
}
