<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * PersistentVolumeClaimStatus is the current status of a persistent volume claim.
 */
class V1PersistentVolumeClaimStatus implements JsonSerializable
{
    /**
     * AccessModes contains the actual access modes the volume backing the PVC has. More info: http://kubernetes.io/docs/user-guide/persistent-volumes#access-modes-1
     * @var array|null $accessModes public property
     */
    public $accessModes;

    /**
     * Represents the actual resources of the underlying volume.
     * @var array|null $capacity public property
     */
    public $capacity;

    /**
     * Phase represents the current phase of PersistentVolumeClaim.
     * @var string|null $phase public property
     */
    public $phase;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $accessModes Initialization value for $this->accessModes
     * @param array  $capacity    Initialization value for $this->capacity
     * @param string $phase       Initialization value for $this->phase
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->accessModes = func_get_arg(0);
            $this->capacity    = func_get_arg(1);
            $this->phase       = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accessModes'] = $this->accessModes;
        $json['capacity']    = $this->capacity;
        $json['phase']       = $this->phase;

        return $json;
    }
}
