<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * PodSecurityPolicySelfSubjectReview checks whether this user/SA tuple can create the PodTemplateSpec
 */
class V1PodSecurityPolicySelfSubjectReview implements JsonSerializable
{
    /**
     * spec defines specification the PodSecurityPolicySelfSubjectReview.
     * @required
     * @var V1PodSecurityPolicySelfSubjectReviewSpec $spec public property
     */
    public $spec;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * status represents the current information/status for the PodSecurityPolicySelfSubjectReview.
     * @var V1PodSecurityPolicySubjectReviewStatus|null $status public property
     */
    public $status;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1PodSecurityPolicySelfSubjectReviewSpec $spec       Initialization value for $this->spec
     * @param string                                   $apiVersion Initialization value for $this->apiVersion
     * @param string                                   $kind       Initialization value for $this->kind
     * @param V1PodSecurityPolicySubjectReviewStatus   $status     Initialization value for $this->status
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->spec       = func_get_arg(0);
            $this->apiVersion = func_get_arg(1);
            $this->kind       = func_get_arg(2);
            $this->status     = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['spec']       = $this->spec;
        $json['apiVersion'] = $this->apiVersion;
        $json['kind']       = $this->kind;
        $json['status']     = $this->status;

        return $json;
    }
}
