<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ProjecRequest is the set of options necessary to fully qualify a project request
 */
class V1ProjectRequest implements JsonSerializable
{
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Description is the description to apply to a project
     * @var string|null $description public property
     */
    public $description;

    /**
     * DisplayName is the display name to apply to a project
     * @var string|null $displayName public property
     */
    public $displayName;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * Standard object's metadata.
     * @var V1ObjectMeta|null $metadata public property
     */
    public $metadata;

    /**
     * Constructor to set initial or default values of member properties
     * @param string       $apiVersion  Initialization value for $this->apiVersion
     * @param string       $description Initialization value for $this->description
     * @param string       $displayName Initialization value for $this->displayName
     * @param string       $kind        Initialization value for $this->kind
     * @param V1ObjectMeta $metadata    Initialization value for $this->metadata
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->apiVersion  = func_get_arg(0);
            $this->description = func_get_arg(1);
            $this->displayName = func_get_arg(2);
            $this->kind        = func_get_arg(3);
            $this->metadata    = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['apiVersion']  = $this->apiVersion;
        $json['description'] = $this->description;
        $json['displayName'] = $this->displayName;
        $json['kind']        = $this->kind;
        $json['metadata']    = $this->metadata;

        return $json;
    }
}
