<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ResourceQuotaSpec defines the desired hard limits to enforce for Quota.
 */
class V1ResourceQuotaSpec implements JsonSerializable
{
    /**
     * Hard is the set of desired hard limits for each named resource. More info: http://releases.k8s.io/HEAD/docs/design/admission_control_resource_quota.md#admissioncontrol-plugin-resourcequota
     * @var array|null $hard public property
     */
    public $hard;

    /**
     * A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects.
     * @var array|null $scopes public property
     */
    public $scopes;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $hard   Initialization value for $this->hard
     * @param array $scopes Initialization value for $this->scopes
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->hard   = func_get_arg(0);
            $this->scopes = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['hard']   = $this->hard;
        $json['scopes'] = $this->scopes;

        return $json;
    }
}
