<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ResourceAttributes includes the authorization attributes available for resource requests to the
 * Authorizer interface
 */
class V1ResourceAttributes implements JsonSerializable
{
    /**
     * Group is the API Group of the Resource.  "*" means all.
     * @var string|null $group public property
     */
    public $group;

    /**
     * Name is the name of the resource being requested for a "get" or deleted for a "delete". "" (empty) means all.
     * @var string|null $name public property
     */
    public $name;

    /**
     * Namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces "" (empty) is defaulted for LocalSubjectAccessReviews "" (empty) is empty for cluster-scoped resources "" (empty) means "all" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview
     * @maps namespace
     * @var string|null $mnamespace public property
     */
    public $mnamespace;

    /**
     * Resource is one of the existing resource types.  "*" means all.
     * @var string|null $resource public property
     */
    public $resource;

    /**
     * Subresource is one of the existing resource types.  "" means none.
     * @var string|null $subresource public property
     */
    public $subresource;

    /**
     * Verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  "*" means all.
     * @var string|null $verb public property
     */
    public $verb;

    /**
     * Version is the API Version of the Resource.  "*" means all.
     * @var string|null $version public property
     */
    public $version;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $group       Initialization value for $this->group
     * @param string $name        Initialization value for $this->name
     * @param string $mnamespace  Initialization value for $this->mnamespace
     * @param string $resource    Initialization value for $this->resource
     * @param string $subresource Initialization value for $this->subresource
     * @param string $verb        Initialization value for $this->verb
     * @param string $version     Initialization value for $this->version
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->group       = func_get_arg(0);
            $this->name        = func_get_arg(1);
            $this->mnamespace  = func_get_arg(2);
            $this->resource    = func_get_arg(3);
            $this->subresource = func_get_arg(4);
            $this->verb        = func_get_arg(5);
            $this->version     = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['group']       = $this->group;
        $json['name']        = $this->name;
        $json['namespace']   = $this->mnamespace;
        $json['resource']    = $this->resource;
        $json['subresource'] = $this->subresource;
        $json['verb']        = $this->verb;
        $json['version']     = $this->version;

        return $json;
    }
}
