<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ResourceRequirements describes the compute resource requirements.
 */
class V1ResourceRequirements implements JsonSerializable
{
    /**
     * Limits describes the maximum amount of compute resources allowed. More info: http://kubernetes.io/docs/user-guide/compute-resources/
     * @var array|null $limits public property
     */
    public $limits;

    /**
     * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: http://kubernetes.io/docs/user-guide/compute-resources/
     * @var array|null $requests public property
     */
    public $requests;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $limits   Initialization value for $this->limits
     * @param array $requests Initialization value for $this->requests
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->limits   = func_get_arg(0);
            $this->requests = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['limits']   = $this->limits;
        $json['requests'] = $this->requests;

        return $json;
    }
}
