<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * RouteTargetReference specifies the target that resolve into endpoints. Only the 'Service' kind is
 * allowed. Use 'weight' field to emphasize one over others.
 */
class V1RouteTargetReference implements JsonSerializable
{
    /**
     * The kind of target that the route is referring to. Currently, only 'Service' is allowed
     * @required
     * @var string $kind public property
     */
    public $kind;

    /**
     * name of the service/target that is being referred to. e.g. name of the service
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * weight as an integer between 1 and 256 that specifies the target's relative weight against other target reference objects
     * @required
     * @var integer $weight public property
     */
    public $weight;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $kind   Initialization value for $this->kind
     * @param string  $name   Initialization value for $this->name
     * @param integer $weight Initialization value for $this->weight
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->kind   = func_get_arg(0);
            $this->name   = func_get_arg(1);
            $this->weight = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['kind']   = $this->kind;
        $json['name']   = $this->name;
        $json['weight'] = $this->weight;

        return $json;
    }
}
