<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * RouteIngress holds information about the places where a route is exposed.
 */
class V1RouteIngress implements JsonSerializable
{
    /**
     * Conditions is the state of the route, may be empty.
     * @var V1ReplicationControllerCondition[]|null $conditions public property
     */
    public $conditions;

    /**
     * Host is the host string under which the route is exposed; this value is required
     * @var string|null $host public property
     */
    public $host;

    /**
     * CanonicalHostname is the external host name for the router that can be used as a CNAME for the host requested for this route. This value is optional and may not be set in all cases.
     * @var string|null $routerCanonicalHostname public property
     */
    public $routerCanonicalHostname;

    /**
     * Name is a name chosen by the router to identify itself; this value is required
     * @var string|null $routerName public property
     */
    public $routerName;

    /**
     * Wildcard policy is the wildcard policy that was allowed where this route is exposed.
     * @var string|null $wildcardPolicy public property
     */
    public $wildcardPolicy;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $conditions              Initialization value for $this->conditions
     * @param string $host                    Initialization value for $this->host
     * @param string $routerCanonicalHostname Initialization value for $this->routerCanonicalHostname
     * @param string $routerName              Initialization value for $this->routerName
     * @param string $wildcardPolicy          Initialization value for $this->wildcardPolicy
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->conditions              = func_get_arg(0);
            $this->host                    = func_get_arg(1);
            $this->routerCanonicalHostname = func_get_arg(2);
            $this->routerName              = func_get_arg(3);
            $this->wildcardPolicy          = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['conditions']              = $this->conditions;
        $json['host']                    = $this->host;
        $json['routerCanonicalHostname'] = $this->routerCanonicalHostname;
        $json['routerName']              = $this->routerName;
        $json['wildcardPolicy']          = $this->wildcardPolicy;

        return $json;
    }
}
