<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * RunAsUserStrategyOptions defines the strategy type and any options used to create the strategy.
 */
class V1RunAsUserStrategyOptions implements JsonSerializable
{
    /**
     * Type is the strategy that will dictate what RunAsUser is used in the SecurityContext.
     * @var string|null $type public property
     */
    public $type;

    /**
     * UID is the user id that containers must run as.  Required for the MustRunAs strategy if not using namespace/service account allocated uids.
     * @var integer|null $uid public property
     */
    public $uid;

    /**
     * UIDRangeMax defines the max value for a strategy that allocates by range.
     * @var integer|null $uidRangeMax public property
     */
    public $uidRangeMax;

    /**
     * UIDRangeMin defines the min value for a strategy that allocates by range.
     * @var integer|null $uidRangeMin public property
     */
    public $uidRangeMin;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $type        Initialization value for $this->type
     * @param integer $uid         Initialization value for $this->uid
     * @param integer $uidRangeMax Initialization value for $this->uidRangeMax
     * @param integer $uidRangeMin Initialization value for $this->uidRangeMin
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->type        = func_get_arg(0);
            $this->uid         = func_get_arg(1);
            $this->uidRangeMax = func_get_arg(2);
            $this->uidRangeMin = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']        = $this->type;
        $json['uid']         = $this->uid;
        $json['uidRangeMax'] = $this->uidRangeMax;
        $json['uidRangeMin'] = $this->uidRangeMin;

        return $json;
    }
}
