<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ScaleSpec describes the attributes of a scale subresource.
 */
class V1ScaleSpec implements JsonSerializable
{
    /**
     * desired number of instances for the scaled object.
     * @var integer|null $replicas public property
     */
    public $replicas;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $replicas Initialization value for $this->replicas
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->replicas = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['replicas'] = $this->replicas;

        return $json;
    }
}
