<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * SecretSpec specifies a secret to be included in a build pod and its corresponding mount point
 */
class V1SecretSpec implements JsonSerializable
{
    /**
     * mountPath is the path at which to mount the secret
     * @required
     * @var string $mountPath public property
     */
    public $mountPath;

    /**
     * secretSource is a reference to the secret
     * @required
     * @var V1LocalObjectReference $secretSource public property
     */
    public $secretSource;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                 $mountPath    Initialization value for $this->mountPath
     * @param V1LocalObjectReference $secretSource Initialization value for $this->secretSource
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->mountPath    = func_get_arg(0);
            $this->secretSource = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['mountPath']    = $this->mountPath;
        $json['secretSource'] = $this->secretSource;

        return $json;
    }
}
