<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ServiceAccountReference specifies a service account and namespace by their names.
 */
class V1ServiceAccountReference implements JsonSerializable
{
    /**
     * Name is the name of the service account.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Namespace is the namespace of the service account.  Service accounts from inside the whitelisted namespaces are allowed to be bound to roles.  If Namespace is empty, then the namespace of the RoleBindingRestriction in which the ServiceAccountReference is embedded is used.
     * @required
     * @maps namespace
     * @var string $mnamespace public property
     */
    public $mnamespace;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $name       Initialization value for $this->name
     * @param string $mnamespace Initialization value for $this->mnamespace
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->name       = func_get_arg(0);
            $this->mnamespace = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']      = $this->name;
        $json['namespace'] = $this->mnamespace;

        return $json;
    }
}
