<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * SelfSubjectRulesReviewSpec adds information about how to conduct the check
 */
class V1SelfSubjectRulesReviewSpec implements JsonSerializable
{
    /**
     * Scopes to use for the evaluation.  Empty means "use the unscoped (full) permissions of the user/groups". Nil means "use the scopes on this request".
     * @required
     * @var array $scopes public property
     */
    public $scopes;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $scopes Initialization value for $this->scopes
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->scopes = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['scopes'] = $this->scopes;

        return $json;
    }
}
