<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * SignatureIssuer holds information about an issuer of signing certificate or key.
 */
class V1SignatureIssuer implements JsonSerializable
{
    /**
     * Common name (e.g. openshift-signing-service).
     * @var string|null $commonName public property
     */
    public $commonName;

    /**
     * Organization name.
     * @var string|null $organization public property
     */
    public $organization;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $commonName   Initialization value for $this->commonName
     * @param string $organization Initialization value for $this->organization
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->commonName   = func_get_arg(0);
            $this->organization = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['commonName']   = $this->commonName;
        $json['organization'] = $this->organization;

        return $json;
    }
}
