<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * SourceRevision is the revision or commit information from the source for the build
 */
class V1SourceRevision implements JsonSerializable
{
    /**
     * type of the build source, may be one of 'Source', 'Dockerfile', 'Binary', or 'Images'
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Git contains information about git-based build source
     * @var V1GitSourceRevision|null $git public property
     */
    public $git;

    /**
     * Constructor to set initial or default values of member properties
     * @param string              $type Initialization value for $this->type
     * @param V1GitSourceRevision $git  Initialization value for $this->git
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->type = func_get_arg(0);
            $this->git  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type'] = $this->type;
        $json['git']  = $this->git;

        return $json;
    }
}
