<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * StatusDetails is a set of additional properties that MAY be set by the server to provide additional
 * information about a response. The Reason field of a Status object defines what attributes will be
 * set. Clients must ignore fields that do not match the defined type of each attribute, and should
 * assume that any attribute may be empty, invalid, or under defined.
 */
class V1StatusDetails implements JsonSerializable
{
    /**
     * The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.
     * @var V1StatusCause[]|null $causes public property
     */
    public $causes;

    /**
     * The group attribute of the resource associated with the status StatusReason.
     * @var string|null $group public property
     */
    public $group;

    /**
     * The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).
     * @var string|null $name public property
     */
    public $name;

    /**
     * If specified, the time in seconds before the operation should be retried.
     * @var integer|null $retryAfterSeconds public property
     */
    public $retryAfterSeconds;

    /**
     * Constructor to set initial or default values of member properties
     * @param array   $causes            Initialization value for $this->causes
     * @param string  $group             Initialization value for $this->group
     * @param string  $kind              Initialization value for $this->kind
     * @param string  $name              Initialization value for $this->name
     * @param integer $retryAfterSeconds Initialization value for $this->retryAfterSeconds
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->causes            = func_get_arg(0);
            $this->group             = func_get_arg(1);
            $this->kind              = func_get_arg(2);
            $this->name              = func_get_arg(3);
            $this->retryAfterSeconds = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['causes']            = $this->causes;
        $json['group']             = $this->group;
        $json['kind']              = $this->kind;
        $json['name']              = $this->name;
        $json['retryAfterSeconds'] = $this->retryAfterSeconds;

        return $json;
    }
}
