<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * StorageClass describes the parameters for a class of storage for which PersistentVolumes can be
 * dynamically provisioned.
 *
 * StorageClasses are non-namespaced; the name of the storage class according to etcd is in ObjectMeta.
 * Name.
 */
class V1StorageClass implements JsonSerializable
{
    /**
     * Provisioner indicates the type of the provisioner.
     * @required
     * @var string $provisioner public property
     */
    public $provisioner;

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
     * @var string|null $apiVersion public property
     */
    public $apiVersion;

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
     * @var string|null $kind public property
     */
    public $kind;

    /**
     * Standard object's metadata. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata
     * @var V1ObjectMeta|null $metadata public property
     */
    public $metadata;

    /**
     * Parameters holds the parameters for the provisioner that should create volumes of this storage class.
     * @var array|null $parameters public property
     */
    public $parameters;

    /**
     * Constructor to set initial or default values of member properties
     * @param string       $provisioner Initialization value for $this->provisioner
     * @param string       $apiVersion  Initialization value for $this->apiVersion
     * @param string       $kind        Initialization value for $this->kind
     * @param V1ObjectMeta $metadata    Initialization value for $this->metadata
     * @param array        $parameters  Initialization value for $this->parameters
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->provisioner = func_get_arg(0);
            $this->apiVersion  = func_get_arg(1);
            $this->kind        = func_get_arg(2);
            $this->metadata    = func_get_arg(3);
            $this->parameters  = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['provisioner'] = $this->provisioner;
        $json['apiVersion']  = $this->apiVersion;
        $json['kind']        = $this->kind;
        $json['metadata']    = $this->metadata;
        $json['parameters']  = $this->parameters;

        return $json;
    }
}
