<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * SubjectAccessReviewStatus
 */
class V1SubjectAccessReviewStatus implements JsonSerializable
{
    /**
     * Allowed is required.  True if the action would be allowed, false otherwise.
     * @required
     * @var bool $allowed public property
     */
    public $allowed;

    /**
     * EvaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request.
     * @var string|null $evaluationError public property
     */
    public $evaluationError;

    /**
     * Reason is optional.  It indicates why a request was allowed or denied.
     * @var string|null $reason public property
     */
    public $reason;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool   $allowed         Initialization value for $this->allowed
     * @param string $evaluationError Initialization value for $this->evaluationError
     * @param string $reason          Initialization value for $this->reason
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->allowed         = func_get_arg(0);
            $this->evaluationError = func_get_arg(1);
            $this->reason          = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['allowed']         = $this->allowed;
        $json['evaluationError'] = $this->evaluationError;
        $json['reason']          = $this->reason;

        return $json;
    }
}
