<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * TCPSocketAction describes an action based on opening a socket
 */
class V1TCPSocketAction implements JsonSerializable
{
    /**
     * Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
     * @required
     * @var string $port public property
     */
    public $port;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $port Initialization value for $this->port
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->port = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['port'] = $this->port;

        return $json;
    }
}
