<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * TokenReviewStatus is the result of the token authentication request.
 */
class V1TokenReviewStatus implements JsonSerializable
{
    /**
     * Authenticated indicates that the token was associated with a known user.
     * @var bool|null $authenticated public property
     */
    public $authenticated;

    /**
     * Error indicates that the token couldn't be checked
     * @var string|null $error public property
     */
    public $error;

    /**
     * User is the UserInfo associated with the provided token.
     * @var V1UserInfo|null $user public property
     */
    public $user;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool       $authenticated Initialization value for $this->authenticated
     * @param string     $error         Initialization value for $this->error
     * @param V1UserInfo $user          Initialization value for $this->user
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->authenticated = func_get_arg(0);
            $this->error         = func_get_arg(1);
            $this->user          = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['authenticated'] = $this->authenticated;
        $json['error']         = $this->error;
        $json['user']          = $this->user;

        return $json;
    }
}
