<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most
 * preferred node(s)
 */
class V1WeightedPodAffinityTerm implements JsonSerializable
{
    /**
     * Required. A pod affinity term, associated with the corresponding weight.
     * @required
     * @var V1PodAffinityTerm $podAffinityTerm public property
     */
    public $podAffinityTerm;

    /**
     * weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
     * @required
     * @var integer $weight public property
     */
    public $weight;

    /**
     * Constructor to set initial or default values of member properties
     * @param V1PodAffinityTerm $podAffinityTerm Initialization value for $this->podAffinityTerm
     * @param integer           $weight          Initialization value for $this->weight
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->podAffinityTerm = func_get_arg(0);
            $this->weight          = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['podAffinityTerm'] = $this->podAffinityTerm;
        $json['weight']          = $this->weight;

        return $json;
    }
}
