<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * WebHookTrigger is a trigger that gets invoked using a webhook type of post
 */
class V1WebHookTrigger implements JsonSerializable
{
    /**
     * allowEnv determines whether the webhook can set environment variables; can only be set to true for GenericWebHook.
     * @var bool|null $allowEnv public property
     */
    public $allowEnv;

    /**
     * secret used to validate requests.
     * @var string|null $secret public property
     */
    public $secret;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool   $allowEnv Initialization value for $this->allowEnv
     * @param string $secret   Initialization value for $this->secret
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->allowEnv = func_get_arg(0);
            $this->secret   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['allowEnv'] = $this->allowEnv;
        $json['secret']   = $this->secret;

        return $json;
    }
}
