<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for
 * example, hits-per-second on an Ingress object).
 */
class V2alpha1ObjectMetricStatus implements JsonSerializable
{
    /**
     * currentValue is the current value of the metric (as a quantity).
     * @required
     * @var string $currentValue public property
     */
    public $currentValue;

    /**
     * metricName is the name of the metric in question.
     * @required
     * @var string $metricName public property
     */
    public $metricName;

    /**
     * target is the described Kubernetes object.
     * @required
     * @var V1CrossVersionObjectReference $target public property
     */
    public $target;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                        $currentValue Initialization value for $this->currentValue
     * @param string                        $metricName   Initialization value for $this->metricName
     * @param V1CrossVersionObjectReference $target       Initialization value for $this->target
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->currentValue = func_get_arg(0);
            $this->metricName   = func_get_arg(1);
            $this->target       = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['currentValue'] = $this->currentValue;
        $json['metricName']   = $this->metricName;
        $json['target']       = $this->target;

        return $json;
    }
}
