<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example,
 * hits-per-second on an Ingress object).
 */
class V2alpha1ObjectMetricSource implements JsonSerializable
{
    /**
     * metricName is the name of the metric in question.
     * @required
     * @var string $metricName public property
     */
    public $metricName;

    /**
     * target is the described Kubernetes object.
     * @required
     * @var V1CrossVersionObjectReference $target public property
     */
    public $target;

    /**
     * targetValue is the target value of the metric (as a quantity).
     * @required
     * @var string $targetValue public property
     */
    public $targetValue;

    /**
     * Constructor to set initial or default values of member properties
     * @param string                        $metricName  Initialization value for $this->metricName
     * @param V1CrossVersionObjectReference $target      Initialization value for $this->target
     * @param string                        $targetValue Initialization value for $this->targetValue
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->metricName  = func_get_arg(0);
            $this->target      = func_get_arg(1);
            $this->targetValue = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['metricName']  = $this->metricName;
        $json['target']      = $this->target;
        $json['targetValue'] = $this->targetValue;

        return $json;
    }
}
