<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target
 * (for example, transactions-processed-per-second). The values will be averaged together before being
 * compared to the target value.
 */
class V2alpha1PodsMetricSource implements JsonSerializable
{
    /**
     * metricName is the name of the metric in question
     * @required
     * @var string $metricName public property
     */
    public $metricName;

    /**
     * targetAverageValue is the target value of the average of the metric across all relevant pods (as a quantity)
     * @required
     * @var string $targetAverageValue public property
     */
    public $targetAverageValue;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $metricName         Initialization value for $this->metricName
     * @param string $targetAverageValue Initialization value for $this->targetAverageValue
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->metricName         = func_get_arg(0);
            $this->targetAverageValue = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['metricName']         = $this->metricName;
        $json['targetAverageValue'] = $this->targetAverageValue;

        return $json;
    }
}
