<?php
/*
 * OpenShiftAPIWithKubernetesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OpenShiftAPIWithKubernetesLib\Models;

use JsonSerializable;

/**
 * HorizontalPodAutoscalerStatus describes the current status of a horizontal pod autoscaler.
 */
class V2alpha1HorizontalPodAutoscalerStatus implements JsonSerializable
{
    /**
     * currentMetrics is the last read state of the metrics used by this autoscaler.
     * @required
     * @var V2alpha1MetricStatus[] $currentMetrics public property
     */
    public $currentMetrics;

    /**
     * currentReplicas is current number of replicas of pods managed by this autoscaler, as last seen by the autoscaler.
     * @required
     * @var integer $currentReplicas public property
     */
    public $currentReplicas;

    /**
     * desiredReplicas is the desired number of replicas of pods managed by this autoscaler, as last calculated by the autoscaler.
     * @required
     * @var integer $desiredReplicas public property
     */
    public $desiredReplicas;

    /**
     * lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods, used by the autoscaler to control how often the number of pods is changed.
     * @var string|null $lastScaleTime public property
     */
    public $lastScaleTime;

    /**
     * observedGeneration is the most recent generation observed by this autoscaler.
     * @var integer|null $observedGeneration public property
     */
    public $observedGeneration;

    /**
     * Constructor to set initial or default values of member properties
     * @param array   $currentMetrics     Initialization value for $this->currentMetrics
     * @param integer $currentReplicas    Initialization value for $this->currentReplicas
     * @param integer $desiredReplicas    Initialization value for $this->desiredReplicas
     * @param string  $lastScaleTime      Initialization value for $this->lastScaleTime
     * @param integer $observedGeneration Initialization value for $this->observedGeneration
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->currentMetrics     = func_get_arg(0);
            $this->currentReplicas    = func_get_arg(1);
            $this->desiredReplicas    = func_get_arg(2);
            $this->lastScaleTime      = func_get_arg(3);
            $this->observedGeneration = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['currentMetrics']     = $this->currentMetrics;
        $json['currentReplicas']    = $this->currentReplicas;
        $json['desiredReplicas']    = $this->desiredReplicas;
        $json['lastScaleTime']      = $this->lastScaleTime;
        $json['observedGeneration'] = $this->observedGeneration;

        return $json;
    }
}
